#!/usr/bin/env bash

set -euo pipefail

CLEAR='\033[0m'
RED='\033[0;31m'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$( cd "$DIR/.." && pwd )"
cd "$DIR"

bail() {
  MESSAGE="$@"
  echo -e "${RED}failed: ${MESSAGE}${CLEAR}"
  exit 1
}

if ! command -v rustup &>/dev/null; then
  bail "missing rustup command"
fi

# install from rust-toolchain
rustup show &>/dev/null

if ! command -v gh &>/dev/null; then
  bail "missing gh command (try \$ brew install gh; gh auth)"
fi

# constants
DRAFT_TAG_999="v999.0.0-alpha.999"

# variables
SKIP_BUILD=false
EXR=false
EXISTING_RELEASE=""
RELEASE=false
TAG=""
PUSH_BINARY_REPO=false
IS_DRAFT=false
BINARY_BRANCH=master
RELEASE_DRAFT_FLAG=""
FORCE_PUSH_BINARY=""

parse_params() {
  while [[ "$#" > 0 ]]; do case $1 in
    --skip-build) SKIP_BUILD=true; shift;;
    # --push-tags) PUSH_TAGS=true; OUTPUT="CHANGELOG.md"; shift;;
    # --gh-release) SAVE=true; OUTPUT="CHANGELOG.md"; shift;;
    --existing-release)
      # e.g. you have a draft already (untagged-...)
      EXR=true; EXISTING_RELEASE="$2"; shift 2;;
    --release) RELEASE=true; shift;;
    --tag) TAG="$2"; shift 2;;
    --push-binary-repo) PUSH_BINARY_REPO=true; shift;;
    --draft) IS_DRAFT=true; shift;;
    --|--help) bail "huh";;
    *) bail "Unknown parameter passed: $1";;
  esac; done
  if $IS_DRAFT; then
    BINARY_BRANCH=draft
    TAG="$DRAFT_TAG_999"
    RELEASE_TAG="$DRAFT_TAG_999"
    FORCE_PUSH_BINARY="--force"
  fi
  if [ -z "$TAG" ]; then bail "empty tag. provide one with --tag TAG"; fi
}

parse_params $@

build() {
  set -euo pipefail
  rustup show
  carthage build --use-xcframeworks --no-skip-current --verbose
  # see https://bugs.swift.org/browse/SR-14257, commment by @cormacrelf
  # `zip -y` is the key here, it preserves the Versions/Current (etc) symlinks inside the frameworks.
  # These otherwise cause `unzip` to fail and SwiftPM to give you "TSCBasic.StringError error 1".
  (cd Carthage/Build \
  && rm -f CiteprocRsKit.xcframework.zip \
  && zip -y -r CiteprocRsKit.xcframework.zip CiteprocRsKit.xcframework)
}

checksum () {
  set +e
  # SHORT_SHA=$(git rev-parse --short "$GITHUB_SHA")
  cd Carthage/Build
  touch Package.swift 
  local CHECKSUM=$(swift package compute-checksum CiteprocRsKit.xcframework.zip)
  rm Package.swift
  echo $CHECKSUM
}

push_binary_repo() {
  local TAG="$1"
  local RELEASE_TAG="$2"
  local CHECKSUM="$3"
  local TMP="$(mktemp -d)"
  trap "rm -rf -- $TMP" EXIT

  local DL=$(gh api "/repos/cormacrelf/CiteprocRsKit/releases/tags/$RELEASE_TAG" -q '.assets[] | select(.name == "CiteprocRsKit.xcframework.zip") | .browser_download_url')
  # could dereference this locally, but this makes sure we pushed it somewhere
  local RELEASE_SHA=$(gh api /repos/cormacrelf/CiteprocRsKit/commits/$TAG -q '.sha')

  if [ -z "$DL" ]; then
    bail "release asset not uploaded: $DL"
  fi

  if [ -z "$RELEASE_SHA" ]; then
    bail "tag $TAG or commit referenced by tag $TAG was not uploaded to GitHub"
  fi

  cd "$TMP"
  git clone https://github.com/cormacrelf/CiteprocRsKit-Binary.git --branch master
  cd CiteprocRsKit-Binary
  # https://stackoverflow.com/a/26961416
  git switch -c $BINARY_BRANCH
  cp -R "$DIR"/Scripts/BinaryPackage/* .
  sed \
    -e "s,XCFRAMEWORK_ZIP_URL,$DL,i" \
    -e "s,XCFRAMEWORK_ZIP_CHECKSUM,$CHECKSUM,i" \
    < "$DIR/Scripts/BinaryPackage/Package.swift" \
    > "./Package.swift"
  git add .
  git commit -m "release $TAG from $RELEASE_SHA" \
             -m "https://github.com/cormacrelf/CiteprocRsKit/releases/tag/$TAG"
  git tag -f -a -m "release $TAG from $RELEASE_SHA" $TAG
  echo $(pwd)
  git push $FORCE_PUSH_BINARY origin $BINARY_BRANCH
  git push --force --tags
  cd "$DIR"
}

upload() {
  set +e
  gh release upload "$1" Carthage/Build/CiteprocRsKit.xcframework.zip
}

edit_release() {
  local TAG="$1"
  local CHECKSUM="$2"
  local RELEASE=$(gh api /repos/cormacrelf/CiteprocRsKit/releases/tags/$TAG -q '.url')
  local BODY=$(gh api /repos/cormacrelf/CiteprocRsKit/releases/tags/$TAG -q '.body')
  local DL=$(gh api /repos/cormacrelf/CiteprocRsKit/releases/tags/$TAG -q '.assets[] | select(.name == "CiteprocRsKit.xcframework.zip") | .browser_download_url')
  if ! (echo $BODY | grep -q $CHECKSUM); then
    echo "patching body"
    gh api -X PATCH $RELEASE -f "body=$BODY\n\nChecksum: $CHECKSUM"
  fi
  echo $DL
}

if $SKIP_BUILD && [[ -f Carthage/Build/CiteprocRsKit.xcframework.zip ]]; then
  echo -n
else
  build
fi

CHECKSUM=$(checksum)

if $IS_DRAFT; then
  gh release delete "$RELEASE_TAG" || echo "no draft release to delete; continuing"
  git push origin ":$TAG" || echo "no tag $DRAFT_TAG_999 on remote"
  git tag -d "$TAG" || echo "no tag $DRAFT_TAG_999 locally"
  git tag -m 'draft/test release' "$TAG"
  git push origin "$TAG"
  RELEASE_TAG=$(gh release create "$TAG" -n "Checksum: $CHECKSUM" | xargs basename)
  upload "$RELEASE_TAG"
elif $EXR; then
  RELEASE_TAG="$EXISTING_RELEASE"
  upload "$RELEASE_TAG"
  edit_release "$RELEASE_TAG" "$CHECKSUM"
elif $RELEASE; then
  RELEASE_TAG=$(gh release create "$TAG" -n "Checksum: $CHECKSUM" | xargs basename)
  upload "$RELEASE_TAG"
fi

if $PUSH_BINARY_REPO && ! [ -z "$TAG" ]; then
  if [ -z "${RELEASE_TAG:-}" ]; then
    bail "release tag unspecified"
  fi

  push_binary_repo "$TAG" "$RELEASE_TAG" "$CHECKSUM"
fi
